FILES =  ProducerConsumer.java Producer.java Consumer.java Buffer.java
all:
	javac -g $(FILES)
run:
	java ProducerConsumer
clean:
	rm *.class
package:
	zip -r Ayush-Adhikari-HW4.zip $(FILES) Makefile README.txt